all: main.exe

Population.o: Population.cc
	g++ -c Population.cc

Angle.o: Angle.cc
	g++ -c Angle.cc
	
Fish.o: Fish.cc
	g++ -c Fish.cc
	
Log.o: Log.cc
	g++ -c Log.cc

main.exe: main.cc
	g++ -c Population.cc Angle.cc Fish.cc Log.cc